RMDIR /s /q CMakeFiles
RMDIR /s /q MUtility.dir
RMDIR /s /q x86
RMDIR /s /q x64
RMDIR /s /q Debug
RMDIR /s /q Release
RMDIR /s /q .vs
del /s /q cmake_install.cmake
del /s /q CMakeCache.txt
del /s /q *.vcxproj*
del /s /q *.sln